### ISSUE TITLE
Provide an interface to initialize an SBOM tree with a keypair 

### ISSUE THREAD

**Issue by abuishgair** [TSELab/SBOMCtl#22]
setup cpabe to provide public key, master key pair, where public key will be used for encryption and both keys will be used to generate private keys for users .
              
_Originally posted by @SantiagoTorres in https://github.com/TSELab/SBOMCtl/pull/20#discussion_r1826367874_

**Comment by marcelamelara** [comment]
@SantiagoTorres do you think this is resolved in the [updated EncryptVisitor](https://github.com/TSELab/SBOMCtl/blob/main/privateSBOMExchange/src/petra/lib/models/__init__.py#L391) ?

**Comment by SantiagoTorres** [comment]
Yup! closing :)
