### ISSUE TITLE
hash all of the data fields in nodes

### ISSUE THREAD

**Issue by abuishgair** [TSELab/SBOMCtl#23]
I think we need to hash all of the data fields in a FieldNode, regardless of whether or not we have encrypted data. This is because we want to be be able to ensure the integrity of the whole node, not just individual fields. The same goes for the other node types.

This will also help us verify that the redaction was actually performed correctly: i.e., if we have encrypted data, we should only have placeholder values in the plain data variables. If we don't hash all of the node variables together, we can't check that this property holds.

_Originally posted by @marcelamelara in https://github.com/TSELab/SBOMCtl/pull/20#discussion_r1826316817_

**Comment by abuishgair** [comment]
@SantiagoTorres  so hashing all data fields excludes children? or hash all node attributes?

**Comment by SantiagoTorres** [comment]
Hash all node attributes, but do not encrypt the children. Otherwise somebody would be able to tamper w/ the structure of the SBOM...
